min-mask-area: 0.001
min-mask-area-final: 0.001
edge-metric: "iou"
cosine-weight: 0.2
metric-threshold: 0.1
model-path: "SAM_model/sam_vit_b.pth"
segments-filename: "segments.pt"
embeddings-filename: "embeddings.pt"
merged-filename: "merged.pt"
vis-filename: "segments.mat"
sam-segments-checkpoint: True
merged-checkpoint: False
points-per-side: 32
points-per-batch: 64
points-per-batch-filtering: 64
pred-iou-thresh: 0.88
stability-score-offset: 1.0
stability-score-thresh: 0.95
box-nms-thresh: 0.7
subviews-batch-size: 1
mask-mask-side-size: 256
std-iou-error-weight: 0.1
ransac-n-fitting-points: 2
ransac-n-inliers: 50
ransac-n-iterations: 10
mask-test-threshold: 0.01
token-size: 1