min-mask-area: 0.001
min-mask-area-final: 0.001
distance-metric: "cosine"
cosine-weight: 0.2
metric-threshold: 0.5
model-path: "SAM_model/sam_vit_b.pth"
segments-filename: "segments.pt"
embeddings-filename: "embeddings.pt"
merged-filename: "merged.pt"
vis-filename: "segments.mat"
sam-segments-checkpoint: True
merged-checkpoint: False
points-per-side: 40
points-per-batch: 64
points-per-batch-filtering: 64
pred-iou-thresh: 0.88
stability-score-offset: 1.0
stability-score-thresh: 0.95
box-nms-thresh: 0.7
batch-size: 1
mask-mask-side-size: 256
std-iou-error-weight: 0.1
mask-test-threshold: 5
k-means-reg-parameter: 0.01
k-means-n-iterations: 100
n-parallel-processes: 1
min-central-segments-for-parallel: 50
token-size: 256
ransac-max-outliers: 0.1
ransac-max-iterations: 15
embedding-coeff: 0.5