exp-name: Urban_Real # experiment identifier
dataset-name: URBAN_REAL # dataset to use. options: [HCI, URBAN_REAL, URBAN_SYN, MMSPG]
continue-progress: False # continue from the file saved in in 'exp-name' folder