exp-name: HCI_TEST # experiment identifier
dataset-name: HCI # dataset to use. options: [HCI, URBAN_REAL, URBAN_SYN, MMSPG]
continue-progress: True # continue from the file saved in in 'exp-name' folder