exp-name: baseline # experiment identifier
dataset-name: URBAN_SYN # dataset to use. options: [HCI, URBAN_REAL, URBAN_SYN, MMSPG]
method-name: baseline # [ours, baseline, salads]
continue-progress: True # continue from the file saved in in 'exp-name' folder