min-mask-area-final: 0.01
min-similarity: 0.85
verbose: False
top-n-segments-visualization: 10
merged-filename: "merged.pt"
merged-checkpoint: False
mask-test-threshold: 5
n-parallel-processes: 1
ransac-max-outliers: 0.05
ransac-max-iterations: 1
embedding-coeff: 1
lambda-reg: 0.3
k-cutoff: 2
subview-percentage: 0.8
k-means-reg-parameter: 0.01
k-means-n-iterations: 100
min-central-segments-for-parallel: 50