min-mask-area-final: 0.001
metric-threshold: 0.2
verbose: True
top-n-segments-visualization: 10
merged-filename: "merged.pt"
vis-filename: "segments.mat"
merged-checkpoint: False
mask-test-threshold: 5
n-parallel-processes: 1
ransac-max-outliers: 0.05
ransac-max-iterations: 1
embedding-coeff: 1
k-means-reg-parameter: 0.01
k-means-n-iterations: 100
min-central-segments-for-parallel: 50