min-similarity: 0.75
lambda-reg: 0.3
k-cutoff: 6

verbose: False
top-n-segments-visualization: 10
n-parallel-processes: 1
k-means-reg-parameter: 0.01
k-means-n-iterations: 100
min-central-segments-for-parallel: 50
min-avg-labels-gt-merger: 100