sam-checkpoint: sam2_checkpoints/sam2.1_hiera_tiny.pt
sam-config: sam2.1_hiera_t.yaml
points-per-side: 64 # default 32
pred-iou-thresh: 0.8 # default 0.8
min-mask-area: 0 # default 0
box-nms-thresh: 0.2 # default 0.7